name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o single-user-sshd-linux-amd64 cmd/.
          GOOS=darwin GOARCH=amd64 go build -o single-user-sshd-darwin-amd64 cmd/.
          GOOS=freebsd GOARCH=amd64 go build -o single-user-sshd-freebsd-amd64 cmd/.

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            single-user-sshd-linux-amd64
            single-user-sshd-darwin-amd64
            single-user-sshd-freebsd-amd64
